### ISSUE TITLE
Only bottom?

### ISSUE THREAD

**Issue by IanWald** [Brian-Masse/ScrollBlur#1]
It is a nice universal script, though it seems to only apply to the bottom of the scrollview rather than the top? Maybe this is intended or I missed a config setting.

**Comment by Brian-Masse** [comment]
The blur automatically only applies to the bottom of the scroll. You can extend the height of the blur with the blurHeight arg. I will work on a quick patch to allow you to pin the blur at the top of the screen.

**Comment by GunpointGaming** [comment]
Got it, thanks for taking the time to do that. I appreciate your quick response

**Comment by Brian-Masse** [comment]
Just pushed a solution, now you can specify the scrollPosition with either .top or .bottom

**Comment by IanWald** [comment]
Thanks for taking the time to do that
